ALTER TABLE drivers
  ADD COLUMN IF NOT EXISTS doc_license TEXT,
  ADD COLUMN IF NOT EXISTS doc_aadhaar TEXT,
  ADD COLUMN IF NOT EXISTS doc_pan TEXT,
  ADD COLUMN IF NOT EXISTS doc_police TEXT,
  ADD COLUMN IF NOT EXISTS license_no TEXT,
  ADD COLUMN IF NOT EXISTS license_exp TEXT,
  ADD COLUMN IF NOT EXISTS photo_url TEXT;
